name = "BasicTreePlots"
uuid = "523fa316-3eda-45c7-ad2f-0d13a1dc3d77"
version = "0.1.0"
authors = ["Benjamin Doran and collaborators"]

[workspace]
projects = ["test", "docs"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NewickTree = "b0a14db8-6308-4ebc-8917-f72cd81f5094"

[extensions]
BasicTreePlotsMakieExt = "Makie"
BasicTreePlotsNewickTreeExt = "NewickTree"

[compat]
AbstractTrees = "0.4"
Makie = "0.24"
NewickTree = "0.4"
OrderedCollections = "1.8.1"
Reexport = "1"
Statistics = "1"
julia = "1.9"

