[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ArgMacros = "dbc42088-9de8-42a0-8ec8-2cd114e1ea3e"
BasicTreePlots = "523fa316-3eda-45c7-ad2f-0d13a1dc3d77"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NewickTree = "b0a14db8-6308-4ebc-8917-f72cd81f5094"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[sources]
BasicTreePlots = {path = ".."}
